import { Command } from 'commander';
import { existsSync, readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

/**
 * `siriusos migrate-paths` rewrites persisted absolute paths after the
 * 0.1.7 → 0.1.8 rename of the install location from ~/cortextos to ~/siriusos.
 *
 * What it touches:
 *   - ~/.siriusos/<instance>/state/agents/<agent>/.siriusos-env
 *   - <projectRoot>/ecosystem.config.js
 *   - ~/Library/LaunchAgents/com.siriusos.*.plist (macOS only)
 *
 * What it does not touch:
 *   - Source files in src/ or community/ (those moved with the carpeta)
 *   - Git history
 *   - Daemon process state (the operator must restart pm2 separately)
 *
 * Exit codes:
 *   0 — migration complete, or nothing to migrate
 *   1 — partial failure, see stderr for details
 */

interface MigrationResult {
  scanned: number;
  modified: number;
  skipped: number;
  errors: string[];
}

const LEGACY = '/cortextos';
const CANONICAL = '/siriusos';

function rewriteFile(path: string, dryRun: boolean, result: MigrationResult): void {
  if (!existsSync(path)) return;
  result.scanned += 1;

  let content: string;
  try {
    content = readFileSync(path, 'utf-8');
  } catch (err) {
    result.errors.push(`Could not read ${path}: ${err instanceof Error ? err.message : err}`);
    return;
  }

  // Only rewrite paths that contain '/cortextos' as a path segment, not
  // arbitrary string matches. We anchor to '/cortextos/' (path-style) and
  // '/cortextos\n' / quoted variants. This avoids touching:
  //   - License/README mentions of "cortextos" (no leading slash)
  //   - Comments that reference the project name historically
  //   - Variable names like `cortextosBin` that source code might still use
  const before = content;
  const after = content
    .replace(/\/cortextos\//g, `${CANONICAL}/`)
    .replace(/\/cortextos$/gm, CANONICAL)
    .replace(/\/cortextos"/g, `${CANONICAL}"`)
    .replace(/\/cortextos'/g, `${CANONICAL}'`);

  if (before === after) {
    result.skipped += 1;
    return;
  }

  if (dryRun) {
    result.modified += 1;
    console.log(`  [dry-run] would rewrite: ${path}`);
    return;
  }

  try {
    writeFileSync(path, after, 'utf-8');
    result.modified += 1;
    console.log(`  rewrote: ${path}`);
  } catch (err) {
    result.errors.push(`Could not write ${path}: ${err instanceof Error ? err.message : err}`);
  }
}

function scanInstanceState(instance: string, dryRun: boolean, result: MigrationResult): void {
  const stateRoot = join(homedir(), '.siriusos', instance, 'state');
  if (!existsSync(stateRoot)) return;

  // Walk state/<bucket>/<agent>/ for .siriusos-env files. The bucket layer
  // is whatever the daemon writes (inbox/inflight/processed/outbox/state/agents).
  // We only care about .siriusos-env which is created by the daemon when it
  // boots an agent and contains absolute paths into the project root.
  const buckets = readdirSync(stateRoot, { withFileTypes: true });
  for (const bucket of buckets) {
    if (!bucket.isDirectory()) continue;
    const bucketDir = join(stateRoot, bucket.name);

    let entries: string[] = [];
    try {
      entries = readdirSync(bucketDir);
    } catch {
      continue;
    }

    for (const agent of entries) {
      const agentDir = join(bucketDir, agent);
      try {
        if (!statSync(agentDir).isDirectory()) continue;
      } catch {
        continue;
      }

      // .siriusos-env is the canonical per-agent env file
      rewriteFile(join(agentDir, '.siriusos-env'), dryRun, result);

      // Some daemons also persist a config snapshot we should rewrite
      rewriteFile(join(agentDir, 'config.json'), dryRun, result);
    }
  }
}

function scanProjectFiles(projectRoot: string, dryRun: boolean, result: MigrationResult): void {
  // ecosystem.config.js sits at the project root and is regenerated by
  // `siriusos ecosystem`. We rewrite it in place so the operator does not
  // have to regenerate before restarting PM2.
  rewriteFile(join(projectRoot, 'ecosystem.config.js'), dryRun, result);
}

function scanLaunchAgents(dryRun: boolean, result: MigrationResult): void {
  const launchAgentsDir = join(homedir(), 'Library', 'LaunchAgents');
  if (!existsSync(launchAgentsDir)) return;

  let entries: string[] = [];
  try {
    entries = readdirSync(launchAgentsDir);
  } catch {
    return;
  }

  for (const entry of entries) {
    if (!entry.startsWith('com.siriusos.') || !entry.endsWith('.plist')) continue;
    rewriteFile(join(launchAgentsDir, entry), dryRun, result);
  }
}

function scanPm2Dump(dryRun: boolean, result: MigrationResult): void {
  // PM2's dump.pm2 stores cwd/script paths for resurrected processes. Without
  // rewriting it, `pm2 resurrect` after a reboot would try to start the
  // daemon from /Users/.../cortextos and fail. The safer alternative is to
  // delete + re-add the daemon (`pm2 delete all && pm2 start ecosystem.config.js
  // && pm2 save`) but rewriting in-place keeps the existing process metadata
  // (env vars set at runtime, restart counts, etc.) intact.
  const dumpPath = join(homedir(), '.pm2', 'dump.pm2');
  rewriteFile(dumpPath, dryRun, result);
}

export const migratePathsCommand = new Command('migrate-paths')
  .description('Rewrite persisted absolute paths from ~/cortextos to ~/siriusos (0.1.7 → 0.1.8 migration)')
  .option('--instance <id>', 'Instance ID', 'default')
  .option('--project-root <path>', 'Project root (defaults to current working directory)')
  .option('--dry-run', 'Show what would change without writing')
  .action((options: { instance: string; projectRoot?: string; dryRun?: boolean }) => {
    const projectRoot = options.projectRoot ?? process.cwd();
    const dryRun = Boolean(options.dryRun);

    console.log('');
    console.log(`SiriusOS migrate-paths${dryRun ? ' (dry-run)' : ''}`);
    console.log(`  instance:    ${options.instance}`);
    console.log(`  projectRoot: ${projectRoot}`);
    console.log(`  rewriting:   ${LEGACY} → ${CANONICAL}`);
    console.log('');

    const result: MigrationResult = { scanned: 0, modified: 0, skipped: 0, errors: [] };

    console.log('Scanning ~/.siriusos/<instance>/state/...');
    scanInstanceState(options.instance, dryRun, result);

    console.log('Scanning project root (ecosystem.config.js)...');
    scanProjectFiles(projectRoot, dryRun, result);

    console.log('Scanning ~/Library/LaunchAgents (macOS plists)...');
    scanLaunchAgents(dryRun, result);

    console.log('Scanning ~/.pm2/dump.pm2...');
    scanPm2Dump(dryRun, result);

    console.log('');
    console.log(`Summary:`);
    console.log(`  files scanned:  ${result.scanned}`);
    console.log(`  files ${dryRun ? 'would be ' : ''}modified: ${result.modified}`);
    console.log(`  files unchanged: ${result.skipped}`);

    if (result.errors.length > 0) {
      console.error('');
      console.error('Errors:');
      for (const err of result.errors) console.error(`  ${err}`);
      process.exit(1);
    }

    if (!dryRun && result.modified > 0) {
      console.log('');
      console.log('Next steps:');
      console.log('  1. cd ~/siriusos && npm link             (refresh global CLI symlink)');
      console.log('  2. pm2 delete all                        (drop stale process metadata)');
      console.log('  3. pm2 start ecosystem.config.js && pm2 save');
      console.log('  4. siriusos status                       (verify agents are running)');
    }
  });
